permalink: /:categories/:title/

name: Full Stack
description: A napkin capital angel investment firm in Vancouver, BC, Canada
# url: http://fullstack.ca
url: http://localhost:4000

author: Boris Mann
